### ISSUE TITLE
Npm error [FIXED]

### ISSUE THREAD

**Issue by rull05** [SomnathDas/Whatsapp-Botto-Re#11]
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'nsfw.txt'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:115:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! whatsapp-botto-re@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the whatsapp-botto-re@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by SomnathDas** [comment]
It'll likely to get fixed in upcoming update  .
Please manually create a text file named nsfw.txt 

Sorry for inconvenience
**Have a good day**
