### ISSUE TITLE
client is not defined [FIXED]

### ISSUE THREAD

**Issue by romaaji** [SomnathDas/Whatsapp-Botto-Re#12]
[SERVER] Server Started!
(node:15220) UnhandledPromiseRejectionWarning: ReferenceError: client is not defined
    at Object.exports.info (/root/Documents/tools/WhatsApp_Bot/aji/Whatsapp-Botto-Re-master(1)/Whatsapp-Botto-Re-master/info.js:5:9)
    at create.then.client (/root/Documents/tools/WhatsApp_Bot/aji/Whatsapp-Botto-Re-master(1)/Whatsapp-Botto-Re-master/index.js:67:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SomnathDas** [comment]
Please make sure that in Index.js at 67 line everything is fine. It's not hard to fix this error , its just code that got mistyped somewhere. You just need to define client properly. I hope you read all necessary documentation about how this project works. If nothing works out, pardon me and please stay tuned for upcoming update to the code. 

Sorry for inconvenience.
**Have a good day**
