### ISSUE TITLE
Parsing error [Fixed]

### ISSUE THREAD

**Issue by KamiSama05** [SomnathDas/Whatsapp-Botto-Re#13]
npm ERR! code EJSONPARSE                                              npm ERR! file /root/Whatsapp-Botto-Re/package.json                    npm ERR! JSON.parse Failed to parse json                              npm ERR! JSON.parse Unexpected token } in JSON at position 691 while parsing near '..."util": "^0.12.3",                                    npm ERR! JSON.parse  },                                               npm ERR! JSON.parse   "devDependencie...'                             npm ERR! JSON.parse Failed to parse package.json data.                npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.                                                                                                                                        npm ERR! A complete log of this run can be found in:                  npm ERR!     /root/.npm/_logs/2020-09-17T04_34_56_262Z-debug.log

**Comment by AlenVelocity** [comment]
This error has been fixed in the [Latest Commit](https://github.com/SomnathDas/Whatsapp-Botto-Re/commit/a252a0dd75d2099403eade5170001385ecc81b10)
