### ISSUE TITLE
error when npm start

### ISSUE THREAD

**Issue by dzakijo1** [SomnathDas/Whatsapp-Botto-Re#15]
![image](https://user-images.githubusercontent.com/47619660/93483834-6fa1b500-f92b-11ea-8829-fc9d7d78a905.png)
how to fix it when npm start?

**Comment by AlenVelocity** [comment]
Please run `npm i bent` or use run `npm i` with the latest commit. If you face any errors like this in the feature please contact me on [Wa](https://wa.me/+919744375687) or [Facebook](https://www.facebook.com/ban.takahiro.5)
