### ISSUE TITLE
How to fix this WAIFU COMMAND

### ISSUE THREAD

**Issue by EthanNoSkill** [SomnathDas/Whatsapp-Botto-Re#20]
[EXEC] 21/09 21:14:50 waifu [0] from 20.NATAN WINSON PRATAMA in KILLER ANIME
TCL: getDUrl -> error Error: Request failed with status code 403
    at createError (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'http://randomwaifu.altervista.org/images/0037.png',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      DNT: 1,
      'Upgrade-Insecure-Requests': 1,
      'User-Agent': 'axios/0.20.0'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'arraybuffer',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      connect: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'randomwaifu.altervista.org',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 2836,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'randomwaifu.altervista.org',
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 2836,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'GET /images/0037.png HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'DNT: 1\r\n' +
      'Upgrade-Insecure-Requests: 1\r\n' +
      'User-Agent: axios/0.20.0\r\n' +
      'Host: randomwaifu.altervista.org\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    insecureHTTPParser: undefined,
    path: '/images/0037.png',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular],
      responseUrl: 'http://randomwaifu.altervista.org/images/0037.png',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'http://randomwaifu.altervista.org/images/0037.png',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      dnt: [Array],
      'upgrade-insecure-requests': [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      date: 'Tue, 22 Sep 2020 03:14:51 GMT',
      server: 'Apache',
      'content-length': '0',
      connection: 'close',
      'content-type': 'text/html; charset=UTF-8'
    },
    config: {
      url: 'http://randomwaifu.altervista.org/images/0037.png',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'arraybuffer',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET /images/0037.png HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'DNT: 1\r\n' +
        'Upgrade-Insecure-Requests: 1\r\n' +
        'User-Agent: axios/0.20.0\r\n' +
        'Host: randomwaifu.altervista.org\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: '/images/0037.png',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: <Buffer >
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
Something went wrong TypeError: Cannot read property 'length' of undefined
    at Client.<anonymous> (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:822:36)
    at step (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
    at C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:34:12)
    at Client.sendImage (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:16)
    at Client.<anonymous> (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:892:33)
    at step (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
(node:9292) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at Client.<anonymous> (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:822:36)
    at step (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
    at C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:38:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:34:12)
    at Client.sendImage (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:817:16)
    at Client.<anonymous> (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:892:33)
    at step (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:63:23)
    at Object.next (C:\Users\ASUS\Whatsapp-Botto-Re\node_modules\@open-wa\wa-automate\dist\api\Client.js:44:53)
(node:9292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlenVelocity** [comment]
For the waifu function we use [this site](http://randomwaifu.altervista.org/). It seems that the monthly bandwidth allowance of this site has Exceeded. It'll be fixed next month hopefully

**Comment by EthanNoSkill** [comment]
Thank you so much for the info Nice bot love it
