### ISSUE TITLE
How to use command kickall and clear all

### ISSUE THREAD

**Issue by EthanNoSkill** [SomnathDas/Whatsapp-Botto-Re#22]
HOW?

**Comment by AlenVelocity** [comment]
Only group creator can use kickall and to use clearall you need to replace your number as the owner variable in [this line](https://github.com/SomnathDas/Whatsapp-Botto-Re/blob/e85c8636c7342484f502a2ac68a82e487a30707c/msgHandler.js#L47) first, then you can use it

**Comment by EthanNoSkill** [comment]
oh

**Comment by EthanNoSkill** [comment]
Are we must using an INDIA number?
Im from Indonesia

**Comment by AlenVelocity** [comment]
No, You can use any number

**Comment by EthanNoSkill** [comment]
How to edit it?

**Comment by EthanNoSkill** [comment]
const owner = '62812xxxxxxxx' // eg 9190xxxxxxxx@

**Comment by EthanNoSkill** [comment]
like that?

**Comment by AlenVelocity** [comment]
Yes, You need to write your full number though

**Comment by EthanNoSkill** [comment]
OH OKAY
