### ISSUE TITLE
Keterangan dalam foto

### ISSUE THREAD

**Issue by NaldoMota1** [SomnathDas/Whatsapp-Botto-Re#25]
Silakan tambahkan fitur keterangan pada foto. Grup lebih bersenang-senang dengan fitur ini

**Comment by AlenVelocity** [comment]
Please state your issue in English

**Comment by NaldoMota1** [comment]
> Informe seu problema em inglês

I told you to add the caption feature to the photos

**Comment by AlenVelocity** [comment]
What do you mean by 

> adding captions to pictures

?

**Comment by NaldoMota1** [comment]
add text to photos

**Comment by AlenVelocity** [comment]
Where?

**Comment by hello124-wq** [comment]
cmd #act welcome  not worked 

cmd #act NSFW not worked

**Comment by SomnathDas** [comment]
@Riocahyapangestu  updated those two commands, please check it out and send me any error message or log file. Thanks
