### ISSUE TITLE
How to use #tsticker command

### ISSUE THREAD

**Issue by JustANewbies** [SomnathDas/Whatsapp-Botto-Re#26]
> hmmmm

**Comment by AlenVelocity** [comment]
Get an api key from [here](https://www.remove.bg/api) and paste your key this this [line](https://github.com/SomnathDas/Whatsapp-Botto-Re/blob/a7b02b4568fddb81b9713d88793944014ce71252/msgHandler.js#L94)

**Comment by ghost** [comment]
dont working
