### ISSUE TITLE
wallpaper command, this is bug?

### ISSUE THREAD

**Issue by gaaak-chan** [SomnathDas/Whatsapp-Botto-Re#30]
- **why i get same photos?**
![WhatsApp Image 2020-10-15 at 10 01 41](https://user-images.githubusercontent.com/72899497/96068056-a1c41980-0ecd-11eb-8fc9-6fe4aa68c011.jpeg)

>  You can fix this? because i dont know how, and im new.

`[EXEC] 15/10 10:00:16 wallpaper [1] from me in test group
{
  success: true,
  wallpapers: [
    {
      id: '672498',
      width: '1920',
      height: '1308',
      file_type: 'jpg',
      file_size: '320695',
      url_image: 'https://images4.alphacoders.com/672/672498.jpg',
      url_thumb: 'https://images4.alphacoders.com/672/thumb-672498.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=672498'
    },
    {
      id: '662285',
      width: '2829',
      height: '2150',
      file_type: 'jpg',
      file_size: '4892856',
      url_image: 'https://images5.alphacoders.com/662/662285.jpg',
      url_thumb: 'https://images5.alphacoders.com/662/thumb-662285.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662285'
    },
    {
      id: '662281',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '3625460',
      url_image: 'https://images8.alphacoders.com/662/662281.png',
      url_thumb: 'https://images8.alphacoders.com/662/thumb-662281.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=662281'
    },
    {
      id: '548268',
      width: '1654',
      height: '930',
      file_type: 'jpg',
      file_size: '483883',
      url_image: 'https://images6.alphacoders.com/548/548268.jpg',
      url_thumb: 'https://images6.alphacoders.com/548/thumb-548268.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548268'
    },
    {
      id: '662283',
      width: '2300',
      height: '960',
      file_type: 'jpg',
      file_size: '1285258',
      url_image: 'https://images2.alphacoders.com/662/662283.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662283.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662283'
    },
    {
      id: '678751',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '1768900',
      url_image: 'https://images7.alphacoders.com/678/678751.jpg',
      url_thumb: 'https://images7.alphacoders.com/678/thumb-678751.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=678751'
    },
    {
      id: '548272',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '1273256',
      url_image: 'https://images2.alphacoders.com/548/548272.jpg',
      url_thumb: 'https://images2.alphacoders.com/548/thumb-548272.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548272'
    },
    {
      id: '662295',
      width: '4081',
      height: '3246',
      file_type: 'jpg',
      file_size: '1295795',
      url_image: 'https://images2.alphacoders.com/662/662295.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662295.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662295'
    },
    {
      id: '677881',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '2748335',
      url_image: 'https://images6.alphacoders.com/677/677881.png',
      url_thumb: 'https://images6.alphacoders.com/677/thumb-677881.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=677881'
    },
    {
      id: '543144',
      width: '1912',
      height: '1080',
      file_type: 'png',
      file_size: '767516',
      url_image: 'https://images8.alphacoders.com/543/543144.png',
      url_thumb: 'https://images8.alphacoders.com/543/thumb-543144.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=543144'
    },
    {
      id: '662292',
      width: '2362',
      height: '1575',
      file_type: 'jpg',
      file_size: '651727',
      url_image: 'https://images6.alphacoders.com/662/662292.jpg',
      url_thumb: 'https://images6.alphacoders.com/662/thumb-662292.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662292'
    },
    {
      id: '678561',
      width: '1920',
      height: '1440',
      file_type: 'jpg',
      file_size: '919240',
      url_image: 'https://images8.alphacoders.com/678/678561.jpg',
      url_thumb: 'https://images8.alphacoders.com/678/thumb-678561.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=678561'
    },
    {
      id: '650804',
      width: '2144',
      height: '1500',
      file_type: 'jpg',
      file_size: '3001887',
      url_image: 'https://images8.alphacoders.com/650/650804.jpg',
      url_thumb: 'https://images8.alphacoders.com/650/thumb-650804.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=650804'
    },
    {
      id: '740339',
      width: '1600',
      height: '900',
      file_type: 'png',
      file_size: '1423748',
      url_image: 'https://images5.alphacoders.com/740/740339.png',
      url_thumb: 'https://images5.alphacoders.com/740/thumb-740339.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=740339'
    },
    {
      id: '548267',
      width: '1680',
      height: '1050',
      file_type: 'jpg',
      file_size: '369958',
      url_image: 'https://images2.alphacoders.com/548/548267.jpg',
      url_thumb: 'https://images2.alphacoders.com/548/thumb-548267.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548267'
    },
    {
      id: '703667',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '475644',
      url_image: 'https://images.alphacoders.com/703/703667.jpg',
      url_thumb: 'https://images.alphacoders.com/703/thumb-703667.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=703667'
    },
    {
      id: '662284',
      width: '4251',
      height: '2988',
      file_type: 'jpg',
      file_size: '4455237',
      url_image: 'https://images2.alphacoders.com/662/662284.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662284.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662284'
    },
    {
      id: '662299',
      width: '2287',
      height: '1434',
      file_type: 'jpg',
      file_size: '3309675',
      url_image: 'https://images7.alphacoders.com/662/662299.jpg',
      url_thumb: 'https://images7.alphacoders.com/662/thumb-662299.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662299'
    },
    {
      id: '662282',
      width: '3500',
      height: '1931',
      file_type: 'jpg',
      file_size: '3576986',
      url_image: 'https://images8.alphacoders.com/662/662282.jpg',
      url_thumb: 'https://images8.alphacoders.com/662/thumb-662282.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662282'
    },
    {
      id: '662286',
      width: '2048',
      height: '1536',
      file_type: 'jpg',
      file_size: '1195039',
      url_image: 'https://images2.alphacoders.com/662/662286.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662286.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662286'
    },
    {
      id: '662300',
      width: '5510',
      height: '3836',
      file_type: 'png',
      file_size: '2210622',
      url_image: 'https://images5.alphacoders.com/662/662300.png',
      url_thumb: 'https://images5.alphacoders.com/662/thumb-662300.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=662300'
    },
    {
      id: '548269',
      width: '1680',
      height: '1050',
      file_type: 'jpg',
      file_size: '134475',
      url_image: 'https://images.alphacoders.com/548/548269.jpg',
      url_thumb: 'https://images.alphacoders.com/548/thumb-548269.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548269'
    },
    {
      id: '740341',
      width: '1920',
      height: '1160',
      file_type: 'png',
      file_size: '2821445',
      url_image: 'https://images7.alphacoders.com/740/740341.png',
      url_thumb: 'https://images7.alphacoders.com/740/thumb-740341.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=740341'
    },
    {
      id: '666089',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '1484100',
      url_image: 'https://images6.alphacoders.com/666/666089.png',
      url_thumb: 'https://images6.alphacoders.com/666/thumb-666089.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=666089'
    },
    {
      id: '681358',
      width: '1900',
      height: '1135',
      file_type: 'jpg',
      file_size: '982377',
      url_image: 'https://images2.alphacoders.com/681/681358.jpg',
      url_thumb: 'https://images2.alphacoders.com/681/thumb-681358.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=681358'
    },
    {
      id: '740333',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '1577515',
      url_image: 'https://images7.alphacoders.com/740/740333.jpg',
      url_thumb: 'https://images7.alphacoders.com/740/thumb-740333.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=740333'
    },
    {
      id: '662301',
      width: '1980',
      height: '1080',
      file_type: 'jpg',
      file_size: '600777',
      url_image: 'https://images5.alphacoders.com/662/662301.jpg',
      url_thumb: 'https://images5.alphacoders.com/662/thumb-662301.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662301'
    },
    {
      id: '662288',
      width: '2400',
      height: '1800',
      file_type: 'jpg',
      file_size: '2961026',
      url_image: 'https://images.alphacoders.com/662/662288.jpg',
      url_thumb: 'https://images.alphacoders.com/662/thumb-662288.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662288'
    },
    {
      id: '751177',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '501286',
      url_image: 'https://images7.alphacoders.com/751/751177.png',
      url_thumb: 'https://images7.alphacoders.com/751/thumb-751177.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=751177'
    },
    {
      id: '662302',
      width: '2516',
      height: '1716',
      file_type: 'png',
      file_size: '1173332',
      url_image: 'https://images8.alphacoders.com/662/662302.png',
      url_thumb: 'https://images8.alphacoders.com/662/thumb-662302.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=662302'
    }
  ],
  total_match: '252'
}
**https://images4.alphacoders.com/672/672498.jpg**

[Client State] TIMEOUT
[Client State] CONNECTED
[Client State] TIMEOUT
[Client State] CONNECTED
[EXEC] 15/10 10:00:41 wallpaper [1] from me in Test grup
{
  success: true,
  wallpapers: [
    {
      id: '672498',
      width: '1920',
      height: '1308',
      file_type: 'jpg',
      file_size: '320695',
      url_image: 'https://images4.alphacoders.com/672/672498.jpg',
      url_thumb: 'https://images4.alphacoders.com/672/thumb-672498.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=672498'
    },
    {
      id: '662285',
      width: '2829',
      height: '2150',
      file_type: 'jpg',
      file_size: '4892856',
      url_image: 'https://images5.alphacoders.com/662/662285.jpg',
      url_thumb: 'https://images5.alphacoders.com/662/thumb-662285.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662285'
    },
    {
      id: '662281',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '3625460',
      url_image: 'https://images8.alphacoders.com/662/662281.png',
      url_thumb: 'https://images8.alphacoders.com/662/thumb-662281.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=662281'
    },
    {
      id: '548268',
      width: '1654',
      height: '930',
      file_type: 'jpg',
      file_size: '483883',
      url_image: 'https://images6.alphacoders.com/548/548268.jpg',
      url_thumb: 'https://images6.alphacoders.com/548/thumb-548268.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548268'
    },
    {
      id: '662283',
      width: '2300',
      height: '960',
      file_type: 'jpg',
      file_size: '1285258',
      url_image: 'https://images2.alphacoders.com/662/662283.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662283.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662283'
    },
    {
      id: '678751',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '1768900',
      url_image: 'https://images7.alphacoders.com/678/678751.jpg',
      url_thumb: 'https://images7.alphacoders.com/678/thumb-678751.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=678751'
    },
    {
      id: '548272',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '1273256',
      url_image: 'https://images2.alphacoders.com/548/548272.jpg',
      url_thumb: 'https://images2.alphacoders.com/548/thumb-548272.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548272'
    },
    {
      id: '662295',
      width: '4081',
      height: '3246',
      file_type: 'jpg',
      file_size: '1295795',
      url_image: 'https://images2.alphacoders.com/662/662295.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662295.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662295'
    },
    {
      id: '677881',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '2748335',
      url_image: 'https://images6.alphacoders.com/677/677881.png',
      url_thumb: 'https://images6.alphacoders.com/677/thumb-677881.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=677881'
    },
    {
      id: '543144',
      width: '1912',
      height: '1080',
      file_type: 'png',
      file_size: '767516',
      url_image: 'https://images8.alphacoders.com/543/543144.png',
      url_thumb: 'https://images8.alphacoders.com/543/thumb-543144.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=543144'
    },
    {
      id: '662292',
      width: '2362',
      height: '1575',
      file_type: 'jpg',
      file_size: '651727',
      url_image: 'https://images6.alphacoders.com/662/662292.jpg',
      url_thumb: 'https://images6.alphacoders.com/662/thumb-662292.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662292'
    },
    {
      id: '678561',
      width: '1920',
      height: '1440',
      file_type: 'jpg',
      file_size: '919240',
      url_image: 'https://images8.alphacoders.com/678/678561.jpg',
      url_thumb: 'https://images8.alphacoders.com/678/thumb-678561.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=678561'
    },
    {
      id: '650804',
      width: '2144',
      height: '1500',
      file_type: 'jpg',
      file_size: '3001887',
      url_image: 'https://images8.alphacoders.com/650/650804.jpg',
      url_thumb: 'https://images8.alphacoders.com/650/thumb-650804.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=650804'
    },
    {
      id: '740339',
      width: '1600',
      height: '900',
      file_type: 'png',
      file_size: '1423748',
      url_image: 'https://images5.alphacoders.com/740/740339.png',
      url_thumb: 'https://images5.alphacoders.com/740/thumb-740339.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=740339'
    },
    {
      id: '548267',
      width: '1680',
      height: '1050',
      file_type: 'jpg',
      file_size: '369958',
      url_image: 'https://images2.alphacoders.com/548/548267.jpg',
      url_thumb: 'https://images2.alphacoders.com/548/thumb-548267.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548267'
    },
    {
      id: '703667',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '475644',
      url_image: 'https://images.alphacoders.com/703/703667.jpg',
      url_thumb: 'https://images.alphacoders.com/703/thumb-703667.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=703667'
    },
    {
      id: '662284',
      width: '4251',
      height: '2988',
      file_type: 'jpg',
      file_size: '4455237',
      url_image: 'https://images2.alphacoders.com/662/662284.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662284.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662284'
    },
    {
      id: '662299',
      width: '2287',
      height: '1434',
      file_type: 'jpg',
      file_size: '3309675',
      url_image: 'https://images7.alphacoders.com/662/662299.jpg',
      url_thumb: 'https://images7.alphacoders.com/662/thumb-662299.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662299'
    },
    {
      id: '662282',
      width: '3500',
      height: '1931',
      file_type: 'jpg',
      file_size: '3576986',
      url_image: 'https://images8.alphacoders.com/662/662282.jpg',
      url_thumb: 'https://images8.alphacoders.com/662/thumb-662282.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662282'
    },
    {
      id: '662286',
      width: '2048',
      height: '1536',
      file_type: 'jpg',
      file_size: '1195039',
      url_image: 'https://images2.alphacoders.com/662/662286.jpg',
      url_thumb: 'https://images2.alphacoders.com/662/thumb-662286.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662286'
    },
    {
      id: '662300',
      width: '5510',
      height: '3836',
      file_type: 'png',
      file_size: '2210622',
      url_image: 'https://images5.alphacoders.com/662/662300.png',
      url_thumb: 'https://images5.alphacoders.com/662/thumb-662300.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=662300'
    },
    {
      id: '548269',
      width: '1680',
      height: '1050',
      file_type: 'jpg',
      file_size: '134475',
      url_image: 'https://images.alphacoders.com/548/548269.jpg',
      url_thumb: 'https://images.alphacoders.com/548/thumb-548269.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=548269'
    },
    {
      id: '740341',
      width: '1920',
      height: '1160',
      file_type: 'png',
      file_size: '2821445',
      url_image: 'https://images7.alphacoders.com/740/740341.png',
      url_thumb: 'https://images7.alphacoders.com/740/thumb-740341.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=740341'
    },
    {
      id: '666089',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '1484100',
      url_image: 'https://images6.alphacoders.com/666/666089.png',
      url_thumb: 'https://images6.alphacoders.com/666/thumb-666089.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=666089'
    },
    {
      id: '681358',
      width: '1900',
      height: '1135',
      file_type: 'jpg',
      file_size: '982377',
      url_image: 'https://images2.alphacoders.com/681/681358.jpg',
      url_thumb: 'https://images2.alphacoders.com/681/thumb-681358.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=681358'
    },
    {
      id: '740333',
      width: '1920',
      height: '1080',
      file_type: 'jpg',
      file_size: '1577515',
      url_image: 'https://images7.alphacoders.com/740/740333.jpg',
      url_thumb: 'https://images7.alphacoders.com/740/thumb-740333.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=740333'
    },
    {
      id: '662301',
      width: '1980',
      height: '1080',
      file_type: 'jpg',
      file_size: '600777',
      url_image: 'https://images5.alphacoders.com/662/662301.jpg',
      url_thumb: 'https://images5.alphacoders.com/662/thumb-662301.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662301'
    },
    {
      id: '662288',
      width: '2400',
      height: '1800',
      file_type: 'jpg',
      file_size: '2961026',
      url_image: 'https://images.alphacoders.com/662/662288.jpg',
      url_thumb: 'https://images.alphacoders.com/662/thumb-662288.jpg',
      url_page: 'https://wall.alphacoders.com/big.php?i=662288'
    },
    {
      id: '751177',
      width: '1920',
      height: '1080',
      file_type: 'png',
      file_size: '501286',
      url_image: 'https://images7.alphacoders.com/751/751177.png',
      url_thumb: 'https://images7.alphacoders.com/751/thumb-751177.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=751177'
    },
    {
      id: '662302',
      width: '2516',
      height: '1716',
      file_type: 'png',
      file_size: '1173332',
      url_image: 'https://images8.alphacoders.com/662/662302.png',
      url_thumb: 'https://images8.alphacoders.com/662/thumb-662302.png',
      url_page: 'https://wall.alphacoders.com/big.php?i=662302'
    }
  ],
  total_match: '252'
}
**https://images4.alphacoders.com/672/672498.jpg** `

>

**Comment by SheIITear** [comment]
Because the command automatically takes the first one which will always be the same, you can do some code that would pick a random result to get better randomness.

**Comment by SomnathDas** [comment]
@gaaak-chan  you can modify the code for better randomization, else we will probably update this feature

**Comment by SheIITear** [comment]
Added in #65
