### ISSUE TITLE
Unlocking notListed commands

### ISSUE THREAD

**Issue by NameawaShinderu** [SomnathDas/Whatsapp-Botto-Re#31]
I wanted to know how do u activate the UNLISTED COMMANDS , nd other json files like quotes , tiktok etc

**Comment by SomnathDas** [comment]
@NameawaShinderu sorry to say that but they're not compatible now

**Comment by NameawaShinderu** [comment]
thanks a lot for replying, btw i m also gwtting a lot of TIMEOUT issues, is this becuz of the FFMPEG site

**Comment by SomnathDas** [comment]
@NameawaShinderu  can you show me a screenshot or describe the issue?
