### ISSUE TITLE
Why Paused?

### ISSUE THREAD

**Issue by MFarelS** [SomnathDas/Whatsapp-Botto-Re#32]
#ask

**Comment by SomnathDas** [comment]
@MFarelS  development has been paused but i'm thinking to continue it soon. It's been paused due to various reasons, some of them are personal but to give you an idea, it's simply as we are getting busier day by day :sweat_smile: 
So don't worry, development is gonna soon be resumed

**Comment by MFarelS** [comment]
> @MFarelS development has been paused but i'm thinking to continue it soon. It's been paused due to various reasons, some of them are personal but to give you an idea, it's simply as we are getting busier day by day 😅
> So don't worry, development is gonna soon be resumed

Yes Resume
