### ISSUE TITLE
can you help me with this?

### ISSUE THREAD

**Issue by abcasker** [SomnathDas/Whatsapp-Botto-Re#33]
![image](https://user-images.githubusercontent.com/74229663/98634057-9c87ac80-235d-11eb-9e14-66b881fcf26d.png)
it ask me to update, and showed me installing patches for 30minues. and whatsapp group link is revoked :))

**Comment by SomnathDas** [comment]
@abcasker Group link has been updated in our Readme file and we are updating the whole repo at this moment so please hold on and try to reinstall all modules

**Comment by AlenVelocity** [comment]
@abcasker  Please Run `npm i @open-wa/wa-automate@3.0.14`

**Comment by abcasker** [comment]
![image](https://user-images.githubusercontent.com/74229663/98635659-5d0e8f80-2360-11eb-9bf6-d952db547c15.png)
do i neef to wait? (thanks for the quick respond)

**Comment by AlenVelocity** [comment]
Yes, It depends on your network

**Comment by abcasker** [comment]
> Yes, It depends on your network

how much storage did it takes?
