### ISSUE TITLE
Video/gif to Sticker

### ISSUE THREAD

**Issue by InushaDeSilva** [SomnathDas/Whatsapp-Botto-Re#41]
This feature is not working how to fix

**Comment by SomnathDas** [comment]
@TentacleSama4254  wait, let me check

**Comment by SomnathDas** [comment]
@TentacleSama4254  updated the repo, try now

**Comment by InushaDeSilva** [comment]
> @TentacleSama4254 updated the repo, try now

wich file?

**Comment by InushaDeSilva** [comment]
now just error at  start

**Comment by VirusLauncher** [comment]
> now just error at start

For welcome.json, it is blank. Add in [] and the bot will start. 

Also, the gif to sticker not working for me.(Do we need modded whatsapp or normal should work?)

**Comment by AlenVelocity** [comment]
@VirusLauncher try installing imageMagick

**Comment by VirusLauncher** [comment]
Got this error
`[EXEC] 25/11 11:52:01 gsticker [0] from Virus Launcher in PPLLLLLL
[ERROR] [Error: ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\Whatsapp-Botto-Re\media\output.gif'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\Administrator\\Desktop\\Whatsapp-Botto-Re\\media\\output.gif'
}`

**Comment by VirusLauncher** [comment]
^I have realized gsticker is for giphy and it didn't work. Also for #sticker not working for animated gifs(No error code).

**Comment by InushaDeSilva** [comment]
Not working

**Comment by rishabh053** [comment]
gsticker and animated sticker is not working

**Comment by AlenVelocity** [comment]
Please use the latest commit and make sure you have libwebp installed

**Comment by SomnathDas** [comment]
> gsticker and animated sticker is not working
> 

Sticker command is functional as of now with latest commit. Please use latest version of our repo
