### ISSUE TITLE
How to set bot admins and limits

### ISSUE THREAD

**Issue by InushaDeSilva** [SomnathDas/Whatsapp-Botto-Re#42]
yeah?

**Comment by VirusLauncher** [comment]
For Bot Admins:
Change Line 55(msgHandley.js) to your number. 
I do not know how to set multiple admins.

For Joining Limits
Check Line 427(msgHandler.js) 
&Line 44(index.js)

**Comment by InushaDeSilva** [comment]
> For Bot Admins:
> Change Line 55(msgHandley.js) to your number.
> I do not know how to set multiple admins.
> 
> For Joining Limits
> Check Line 427(msgHandler.js)
> &Line 44(index.js)

Still get the message saying only bot admins can use this command

**Comment by VirusLauncher** [comment]
![WhatsApp Image 2020-11-26 at 11 25 05 PM](https://user-images.githubusercontent.com/59482589/100407401-adfbd480-303e-11eb-8075-dbc93d9b4adf.jpeg)

It working fine for me by changing line55.

**Comment by AlenVelocity** [comment]
You can add an array of numbers which you can use as bot admins [here](https://github.com/SomnathDas/Whatsapp-Botto-Re/blob/0966f33972ab9815f6a60769772fbeb9c75ed4ec/msgHandler.js#L61)
