### ISSUE TITLE
Unlisted commands

### ISSUE THREAD

**Issue by InushaDeSilva** [SomnathDas/Whatsapp-Botto-Re#43]
Anyway I can cativete the unlisted command for fun replies and stuff?

**Comment by VirusLauncher** [comment]
#31

**Comment by InushaDeSilva** [comment]
> #31

Seems to be not sovled

**Comment by AlenVelocity** [comment]
It logs [Unlisted] if the command received is not in the switch case

**Comment by AlenVelocity** [comment]
You can add commands by adding a new case and defining is
