### ISSUE TITLE
Grouplink

### ISSUE THREAD

**Issue by InushaDeSilva** [SomnathDas/Whatsapp-Botto-Re#49]
the support grouplink is outdated

**Comment by AlenVelocity** [comment]
https://chat.whatsapp.com/DSz1dsJ4mLjBAhj1a6Dsaf

**Comment by AlenVelocity** [comment]
Sorry about that

**Comment by SomnathDas** [comment]
> the support grouplink is outdated

Group link has been updated in Readme 
Thank you and have a great day
