### ISSUE TITLE
Termux working

### ISSUE THREAD

**Issue by techakhil272** [SomnathDas/Whatsapp-Botto-Re#52]
Will this work for termux
How can this work for termux

**Comment by SomnathDas** [comment]
> Will this work for termux
> How can this work for termux

I'm not sure if this will work in termux cuz I never tried but you can try but nonetheless I recommend you to use a pc with Linux or windows.

**Comment by AlenVelocity** [comment]
No it's not possible. You might want to check out [Baileys](https://github.com/adiwajshing/Baileys) if you wish to run bots in termux
