### ISSUE TITLE
Is it possible to generate the exif file dynamically ???

### ISSUE THREAD

**Issue by IslamYA** [SomnathDas/Whatsapp-Botto-Re#54]
Is it possible to generate the exif file dynamically like the one in
media/sticker/data.exif ?

or how its made in general ?
i tried to hex edit yours but cant get it to work

thanks for the this awesome repo

**Comment by SomnathDas** [comment]
> Is it possible to generate the exif file dynamically like the one in
> media/sticker/data.exif ?
> 
> or how its made in general ?
> i tried to hex edit yours but cant get it to work
> 
> thanks for the this awesome repo
> 

Join our Whatsapp group and we'll discuss it there
 https://chat.whatsapp.com/DSz1dsJ4mLjBAhj1a6Dsaf

Have a great day! 🎄

**Comment by IslamYA** [comment]
thank you very much ♥️

i joined the whatsapp group

**Comment by InushaDeSilva** [comment]
deth

**Comment by AlenVelocity** [comment]
Eye Emoji
