### ISSUE TITLE
Error: Could not find browser revision 818858.

### ISSUE THREAD

**Issue by DjKagetane** [SomnathDas/Whatsapp-Botto-Re#59]
@AlenSaito1 @SomnathDas 
![image](https://user-images.githubusercontent.com/74662437/103009960-4a1ddc00-4516-11eb-978b-ce5815871b74.png)

**Comment by AlenVelocity** [comment]
Please re-install the modules

**Comment by SomnathDas** [comment]
#11

**Comment by SomnathDas** [comment]
#19

**Comment by SomnathDas** [comment]
Same as #67
