### ISSUE TITLE
BUG VIDEO/GIF TO STICKER

### ISSUE THREAD

**Issue by sudimantidio** [SomnathDas/Whatsapp-Botto-Re#71]
![image_2021-01-20_082244](https://user-images.githubusercontent.com/77594127/105114039-ac0f3880-5af8-11eb-8306-0db81eed8ae8.png)

I installed like Ffmpeg,
ImageMagick,
Libwebp (optional) but when sending a video / gif it gets an error like in the picture

**Comment by SomnathDas** [comment]
Check if you provided the correct path.
It's almost always related to the path.

**Comment by SomnathDas** [comment]
Also make sure folders and files are on the location where they're supposed to be at.
