### ISSUE TITLE
Problem with QR code

### ISSUE THREAD

**Issue by SavageJoshi** [SomnathDas/Whatsapp-Botto-Re#79]
When ever I try to scan the QR code with my whatsapp web, it scans it and returns an error saying "The session is invalid.Retrying" and gives me another code. And same happens for another QR too, and **this happens in loop**.
I tried using useChrome to true as well as false but doesnt help.
Please can you guide me through this
![Screenshot (114)](https://user-images.githubusercontent.com/80508907/110905551-a67fe300-8330-11eb-989a-551f742fc359.png)

**Comment by SomnathDas** [comment]
@SavageJoshi  Please make sure to tell others how you fixed it before closing the issue. It will probably help others uwu)/
